# Generated by Django 3.2 on 2024-06-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quantity_rating',
            new_name='quality_rating',
        ),
    ]
